<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abbreviation' => '',
    'App Config Groups' => '',
    'App Config Types' => '',
    'App Configs' => '',
    'App ID' => '',
    'App Users' => '',
    'Apps' => '',
    'Are you sure you want to delete this item?' => '',
    'Cities' => '',
    'City ID' => '',
    'Companies' => '',
    'Company ID' => '',
    'Config Group ID' => '',
    'Config Type ID' => '',
    'Country' => '',
    'Create App' => '',
    'Create App Config' => '',
    'Create App Config Group' => '',
    'Create App Config Type' => '',
    'Create App User' => '',
    'Create City' => '',
    'Create Company' => '',
    'Create Department' => '',
    'Create Person' => '',
    'Create Schedule' => '',
    'Create Schedule Log' => '',
    'Created At' => '',
    'Creation Date' => '',
    'Delete' => '',
    'Department ID' => '',
    'Departments' => '',
    'Description' => '',
    'Email' => '',
    'End Date' => '',
    'End Time' => '',
    'Expiration Date' => '',
    'Frequency Type' => '',
    'ID' => '',
    'Information' => '',
    'Is Active' => '',
    'Last Execution' => '',
    'Manager' => '',
    'Manager Name' => '',
    'Manager Phone' => '',
    'Mobile Phone' => '',
    'Name' => '',
    'Next Execution' => '',
    'Order' => '',
    'People' => '',
    'Person ID' => '',
    'Phone' => '',
    'Repeat Interval' => '',
    'Reset' => '',
    'Save' => '',
    'Schedule Logs' => '',
    'Schedules' => '',
    'Search' => '',
    'Ssn' => '',
    'Start Date' => '',
    'Start Time' => '',
    'State' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update App Config Group: mode' => '',
    'Update App Config Type: mode' => '',
    'Update App Config: mode' => '',
    'Update App User: mode' => '',
    'Update App: mode' => '',
    'Update City: mode' => '',
    'Update Company: mode' => '',
    'Update Department: mode' => '',
    'Update Person: mode' => '',
    'Update Schedule Log: mode' => '',
    'Update Schedule: mode' => '',
    'Updated At' => '',
    'Username' => '',
    'Value' => '',
];
