<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Abbreviation' => 'Sigla',
    'App Config Groups' => 'Grupo de Configuração do Aplicativo',
    'App Config Types' => 'Tipo ed configuração do Aplicativo',
    'App Configs' => 'Configurações do aplicativo',
    'App ID' => '',
    'App Users' => 'Usuários do sistema',
    'Apps' => 'Sistemas',
    'Are you sure you want to delete this item?' => '',
    'Cities' => 'Cidades',
    'City ID' => '',
    'Companies' => 'Empresas',
    'Company ID' => '',
    'Config Group ID' => '',
    'Config Type ID' => '',
    'Country' => 'País',
    'Create App' => 'Novo aplicativo',
    'Create App Config' => 'Nova configuração',
    'Create App Config Group' => 'Novo grupo',
    'Create App Config Type' => 'Novo tipo',
    'Create App User' => 'Novo usuário',
    'Create City' => 'Nova cidade',
    'Create Company' => 'Nova empresa',
    'Create Department' => 'Novo departamento',
    'Create Person' => 'Nova pessoa',
    'Create Schedule' => 'Novo agendamento',
    'Create Schedule Log' => 'Novo log de agendamento',
    'Created At' => 'Criado em',
    'Creation Date' => 'Data de criação',
    'Delete' => 'Excluir',
    'Department ID' => '',
    'Departments' => 'Departamento',
    'Description' => 'Descrição',
    'Email' => '',
    'End Date' => 'Data final',
    'End Time' => 'Hora final',
    'Expiration Date' => 'Data de expiração',
    'Frequency Type' => 'Frequência',
    'ID' => '',
    'Information' => 'Informação',
    'Is Active' => 'Está ativo?',
    'Last Execution' => 'Última execução',
    'Manager' => 'Responsável',
    'Manager Name' => 'Nome do responsável',
    'Manager Phone' => 'Telefone do responsável',
    'Mobile Phone' => 'Celular',
    'Name' => 'Nome',
    'Next Execution' => 'Próxima execução',
    'Order' => 'Ordem',
    'People' => 'Pessoas',
    'Person ID' => '',
    'Phone' => 'Nº de telefone',
    'Repeat Interval' => 'Intervalo de repetição',
    'Reset' => '',
    'Save' => 'Salvar',
    'Schedule Logs' => 'Logs de Agendamento',
    'Schedules' => 'Agendamentos',
    'Search' => 'Pesquisa',
    'Ssn' => 'CPF',
    'Start Date' => 'Data inicial',
    'Start Time' => 'Hora inicial',
    'State' => 'Estado',
    'The requested page does not exist.' => 'A página não existe',
    'Update' => 'Atualizar',
    'Update App Config Group: ' => 'Atualizar grupo de configuração',
    'Update App Config Type: ' => 'Atualizar tipo de configuração',
    'Update App Config: ' => '',
    'Update App User: ' => '',
    'Update App: ' => '',
    'Update City: ' => 'Atualizar cidade',
    'Update Company: ' => 'Atualizar empresa',
    'Update Department: ' => 'Atualizar departamento',
    'Update Person: ' => 'Atualizar pessoa',
    'Update Schedule Log: ' => '',
    'Update Schedule: ' => '',
    'Updated At' => 'Atualizado em',
    'Username' => 'Nome de usuário',
    'Value' => 'Valor',
];
